openapi: 3.0.1
info:
  title: Lamoda test
  description: Api for managing a warehouse
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080
paths:
  /warehouse/items/reserve:
    post:
      summary: Reserve a list of items based on their unique code
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/codes'
      responses:
        '200':
          description: OK
          content: {}
        '400':
          description: Bad request
          content: {}
  /warehouse/items/release:
    post:
      summary: Release a list of items from reservation based on their unique code
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/codes'
      responses:
        '200':
          description: OK
          content: {}
        '400':
          description: Bad request
          content: {}
  /warehouse/items/left:
    post:
      summary: Remove a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WarehouseId'
      responses:
        '200':
          description: OK
          content: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetLeftResp'
components:
  schemas:
    codes:
      type: object
      properties:
        codes:
          type: array
          items:
            type: string
            default: "uniquecode"
    WarehouseId:
      type: object
      properties:
        id:
          type: integer
          default: 1
    GetLeftResp:
      type: array
      items:
        type: object
        properties:
          item_title:
            type: string
            default: "hoodie"
          item_code:
            type: string
            default: "eelb2"
          reserved:
            type: boolean
            default: false
          quantity:
            type: integer
            default: 0
          warehouse_title:
            type: string
            default: "main"